Update jumbotron
armada-ths/old.armada.nu pull request #479
Opened 2020-06-29 08:58 UTC by ellaklara

2020-07-07 09:30 UTC, Adamih requested changes
Har ett par saker som jag skulle vilja se. Peta på mig om du inte håller med, annars overall väldigt bra jobbat!

2020-07-07 09:30 UTC, Adamih commented on src/components/HamburgerButton/index.js
> +                className={`hamburger-button ${isActive ? ' active' : ''} ${melon ? 'melon' : ''}`}>
Skulle rekommendera att använda biblioteket "classnames" istället. Det används flitigt och är bra för denna typ av kod bland annat. En lösning med classnames skulle se ut så här:

cls = classNames({
    'hamburger-button': true,
    'active': isActive,
    'melon': melon
})
className={cls}

2020-07-07 09:30 UTC, Adamih commented on src/components/Jumbotron/index.js
> +    const [onMobile, setOnMobile] = useState(windowSize.width < 850);
Skulle rekommendera att istället använda biblioteket https://www.npmjs.com/package/react-device-detect

Exempel:
import {isMobile} from 'react-device-detect';

2020-07-07 11:04 UTC, ellaklara commented on src/components/Jumbotron/index.js
> +    const [onMobile, setOnMobile] = useState(windowSize.width < 850);
I'll write in English in case non-Swedish speakers would want to read this in the future.
The hook works better with the Jumbotron video, if you use isMobile instead of "onMobile" the video will remain on the homepage if you resize to mobile-size (or use device tools) on desktop and vice-versa. I know it's a very specific use-case, but I use it all the time when developing, so would it be OK if I kept it that way? It's very annoying having to refresh it constantly.

2020-07-14 10:14 UTC, Adamih commented on src/components/Jumbotron/index.js
> +    const [onMobile, setOnMobile] = useState(windowSize.width < 850);
Ok, i'm not sure that we have tested all the use cases (landscape mode, highres phones etc.), but if issues show up we can fix it then. Good job!

2020-07-14 10:14 UTC, Adamih approved these changes
LGTM!

2020-07-14 10:15 UTC, merged