📧  New email form component
armada-ths/old.armada.nu pull request #608
Opened 2021-10-04 20:05 UTC by vilmaviola

**What's new?** 🤪
- An email form component

**Screenshot** 📸
![Screenshot 2021-10-04 at 21 57 48](https://user-images.githubusercontent.com/45494524/135916131-8f5f15d7-3014-4908-b51e-58c9c29a5371.png)

**Other comments** 🥱
- The adress to which the email will be sent is added as a prop depending on where the component is used
- Clicking on send will open upp the mail application with the fields filled in

**Linked issue** 🤓
 feat: new email form component #607

2021-10-06 08:53 UTC, annagustavsson requested changes
Good job!🤩 Looks really nice. I dropped some comments, feel free to write to me on slack if something seems unclear.

2021-10-06 08:53 UTC, annagustavsson commented on src/components/EmailForm/index.js
> +const EmailForm = (props) => {
Just for clarity, the props could be written out here. `const EmailForm = ({emailTo, otherPropName}) => {` 😊

2021-10-06 08:53 UTC, annagustavsson commented on src/components/EmailForm/index.js
> +    const [formData, setFormData] = useState({
This state could be moved outside the component and sent in like props. So that if we would want to e.g clear the form, this could be done in the parent component, otherwise we would have to hardcode/make it non-dynamic in this component. 🤓

2021-10-06 11:47 UTC, vilmaviola commented on src/components/EmailForm/index.js
> +const EmailForm = (props) => {
Yes that will be easier to understand!

2021-10-06 11:51 UTC, vilmaviola commented on src/components/EmailForm/index.js
> +const EmailForm = (props) => {
It didn't work to have it exactly like you wrote tho 😕
I changed it to this instead so it still will be a bit easier to understand:

const EmailForm = (props) => {
    const { emailTo } = props

2021-10-06 13:42 UTC, vilmaviola commented on src/components/EmailForm/index.js
> +    const [formData, setFormData] = useState({
I don't think I understand what you mean tbh🙈

2021-10-14 12:37 UTC, linnea-bonnevier requested changes
LGTM and works great! :)  
However I would suggest the use of a button instead of a link to send, just makes it more obvious and clear.

2021-10-17 16:24 UTC, annagustavsson commented on src/components/EmailForm/index.js
> +    const [formData, setFormData] = useState({
I thought this was an input-form component that we would maybe wanna use in other places as well, that's why I thought it would be convenient to have access to the data from the parent component. But now I see it's a component only dedicated to sending an email. So never mind what I commented😅

2021-10-18 07:01 UTC, linnea-bonnevier approved these changes
Amazing :) Great work

2021-10-18 07:02 UTC, merged