Annagu/new nav bar
armada-ths/old.armada.nu pull request #613
Opened 2021-10-17 15:45 UTC by annagustavsson

2021-10-18 10:40 UTC, vilmaviola requested changes
Looks great! Love the new menu bar - good job!😍
I just had some nitpicky comments about using const 🤓

2021-10-18 10:40 UTC, vilmaviola commented on src/components/Navbar/index.js
>    var links = menuPages.map((page, index) => (
I haven't seen var being used in a while and googled why, here's a nice article that sums up why: https://medium.com/@codingsam/awesome-javascript-no-more-var-working-title-999428999994

I think we should try and use const or let instead of var. In this case const 😎

2021-10-18 10:40 UTC, vilmaviola commented on src/components/Navbar/index.js
> +  var studentMenu = (
Use const instead 😎

2021-10-18 10:40 UTC, vilmaviola commented on src/components/Navbar/index.js
> +  var companyMenu = (
Use const instead 😎

2021-10-18 10:40 UTC, vilmaviola commented on src/components/Navbar/index.js
> +  var aboutMenu = (
Use const instead 😎

2021-10-19 12:17 UTC, linnea-bonnevier requested changes
Looks great and both web and mobile versions work amazingly ☺️
But from the Navbar index.js file gives me the following errors when trying to build locally, would be great if they could be solved 🌼

<img width="1100" alt="Screenshot 2021-10-19 at 14 13 19" src="https://user-images.githubusercontent.com/62845882/137907033-b1bd8ade-d8ef-4d1d-a5b1-f15b02d7c3c8.png">

2021-11-02 08:13 UTC, linnea-bonnevier approved these changes
Looks good to me :) Let's update our website 🎉🌼

2021-11-02 08:14 UTC, merged