Hilda/issue/630
armada-ths/old.armada.nu pull request #631
Opened 2021-11-10 19:07 UTC by robertssonhilda

Add links to graduateland in navbar and homepage

2021-11-11 09:32 UTC, vilmaviola requested changes
Great job adding it to many places so the users can't miss it! 🙌
I only had a few comments😊  And also a general question, is "graduateland" and "the virutual fair" the same thing?

2021-11-11 09:32 UTC, vilmaviola commented on src/components/Jumbotron/index.js
> +                <a alt="Virtual Fair 2021" href="https://event.armada.nu/">Visit the Virtual Fair</a>
I don't know if it's possible to style this link but it would look nice I think if the text of this link was even bigger (in the same size as the rest of the text in the jumbotron), or what do you think? :)

2021-11-11 09:32 UTC, vilmaviola commented on src/components/Navbar/index.js
> +  const dropdownParent = !onMobile ? ['dropdownParent', 'hoverWeb'].join(" ")
The dropdown in the navbar doesn't work for me when I test your branch 😕

2021-11-11 09:32 UTC, vilmaviola commented on src/components/Navbar/index.js
> +            <a className='left' alt="Virtual Fair 2021" href="https://event.armada.nu/">Virtual Fair</a>
Nice! Now they can't miss it since it's everywhere 🙌

2021-11-11 16:19 UTC, robertssonhilda commented on src/components/Navbar/index.js
> +  const dropdownParent = !onMobile ? ['dropdownParent', 'hoverWeb'].join(" ")
That is weird! It works for me. What is it that's not working?

2021-11-11 16:20 UTC, robertssonhilda commented on src/components/Jumbotron/index.js
> +                <a alt="Virtual Fair 2021" href="https://event.armada.nu/">Visit the Virtual Fair</a>
Yeah, that´s a good input! 

Can´t answer your question about graduateland/virtual fair above: but yes, it is the same thing. Do you think it should say graduateland instead of virtual fair?

2021-11-11 16:30 UTC, robertssonhilda commented on src/components/Jumbotron/index.js
> +                <a alt="Virtual Fair 2021" href="https://event.armada.nu/">Visit the Virtual Fair</a>
![armada](https://user-images.githubusercontent.com/62420861/141333686-a7ce1651-b7dc-48a6-87b2-f6ee0a8a66a1.JPG)

Now it looks like this.

2021-11-12 11:28 UTC, vilmaviola approved these changes
Great job 🤩

2021-11-14 15:02 UTC, linnea-bonnevier commented
Looks good for me as well💯😄

2021-11-14 15:03 UTC, merged